// Generated by CoffeeScript 1.6.3
(function() {
  var Convos, WSC, WebSocketServer, connect, http, server, source, wss;

  http = require("http");

  connect = require("connect");

  WebSocketServer = require('ws').Server;

  WSC = require('../WSC.js');

  Convos = require('./Convos.js').convos;

  source = connect().use(connect["static"](__dirname + '/'));

  server = http.createServer(source).listen(3000, function() {
    return console.log(" server listening");
  });

  wss = new WebSocketServer({
    server: server
  });

  wss.on("connection", function(ws) {
    var wsc;
    console.log("client connected to wss");
    wsc = new WSC.WSC(ws);
    console.log(Convos);
    wsc.addConversations(Convos);
    return ws.on('message', function(data, flags) {
      var msg;
      msg = JSON.parse(data);
      return wsc.onmessage(msg);
    });
  });

}).call(this);
