// Generated by CoffeeScript 1.6.3
(function() {
  var Con;

  Con = require('../WSC.js').Conversation;

  exports.convos = [
    new Con('helloWorld', function(data) {
      return 'hello world ' + data;
    }), new Con('returnEvens', function(data) {
      return data.filter(function(i) {
        return (i % 2) === 0;
      });
    })
  ];

}).call(this);
