// Generated by CoffeeScript 1.6.3
(function() {
  var Conversation, WSC;

  WSC = (function() {
    function WSC(ws) {
      this.ws = ws;
    }

    WSC.prototype.conversations = [];

    WSC.prototype.onmessage = function(msg) {
      var con;
      con = (this.conversations.filter(function(c) {
        return c.name === msg.request;
      }))[0];
      console.log(con);
      return this.ws.send(JSON.stringify({
        response: con.name,
        data: con.respond(msg.data)
      }));
    };

    WSC.prototype.addConversations = function(cons) {
      return this.conversations = this.conversations.concat(cons);
    };

    return WSC;

  })();

  Conversation = (function() {
    function Conversation(name, respond) {
      this.name = name;
      this.respond = respond;
      return this;
    }

    return Conversation;

  })();

  /*
  con.name = 'helloWorld'
  con.respond = (data) -> {response:'helloWorld', data:'hello world!'}
  */


  exports.WSC = WSC;

  exports.Conversation = Conversation;

}).call(this);
