// Generated by CoffeeScript 1.6.3
(function() {
  var Conversation, WSC;

  WSC = (function() {
    function WSC(ws) {
      this.ws = ws;
    }

    WSC.prototype.conversations = {};

    WSC.prototype.onmessage = function(msg) {
      var con;
      con = this.conversations[msg.request];
      console.log(con);
      return this.ws.send(JSON.stringify({
        response: con.name,
        data: con.respond(msg.data)
      }));
    };

    WSC.prototype.addConversations = function(cons) {
      var con, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = cons.length; _i < _len; _i++) {
        con = cons[_i];
        _results.push(this.conversations[con.name] = con.respond);
      }
      return _results;
    };

    return WSC;

  })();

  Conversation = (function() {
    function Conversation(name, respond) {
      this.name = name;
      this.respond = respond;
      return this;
    }

    return Conversation;

  })();

  /*
  con.name = 'helloWorld'
  con.respond = (data) -> {response:'helloWorld', data:'hello world!'}
  */


  exports.WSC = WSC;

  exports.Conversation = Conversation;

}).call(this);
